apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-application-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: list-application-set-app1
            repoURL: https://github.com/OpsMx/argo-customer-demo.git          #pod
            targetRevision: testcase
            path: source-data/application-set-data/list-data/app1
          - name: list-application-set-app2
            repoURL: https://github.com/OpsMx/argo-customer-demo.git           #service
            targetRevision: testcase
            path: source-data/application-set-data/list-data/app2
  template:
    metadata:
      name: '{{name}}'
      labels:
        for: jpmc
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
