apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-matrix-multicm-myplugin
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - matrix:
          generators:
          - git:
              repoURL: "https://github.com/OpsMx/argo-customer-demo.git"
              revision: "gitreqtest1"
              files:
                - path: "base2/*/config.json"
              requeueAfterSeconds: 30
          - git:
              repoURL: "https://github.com/OpsMx/argo-customer-demo.git"
              revision: "gitreqtest1"
              files:
                - path: "base3/*/config.json"
              requeueAfterSeconds: 30
      - plugin:
          configMapRef:
            name: applicationset-hello-plugin
          input:
            parameters:
              repo: "OpsMx/argo-customer-demo"
              branch: "testcase"
              folder: "source-data/pluginfiles"
          #requeueAfterSeconds: 30
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
          - key: syncWave
            operator: In
            values:
              - zero
          maxUpdate: 50%
        - matchExpressions:
          - key: syncWave
            operator: In
            values:
              - one
          maxUpdate: 50%
  template:
    metadata:
      name: '{{.name}}-{{ .label }}'
      annotations:
        myananotation: '{{ .label }}'
      labels:
        syncWave: '{{ .syncWave }}'
        for: jpmc
    spec:
      project: default
      source:
        repoURL: "https://github.com/OpsMx/argo-customer-demo.git"
        path: source-data/multicm-plugin-helm
        targetRevision: testcase
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.name}}-{{ .label }}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 7m
  templatePatch: |
    spec:
      source:
        helm:
          parameters:
          {{- if .contents }}
          {{- range $fileName, $fileContents := .contents }}
            - name: 'configMapFiles.{{ $fileName | replace "." "\\." }}'
              value: '{{ $fileContents }}'
          {{- end }}
            - name: "name"
              value: '{{.name}}'
          {{- end }}
