apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_PORT: "8080"
  
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx1:latest
    ports:
    - containerPort: 80
---
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  #ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: my-job
    spec:
      containers:
      - name: my-job-container
        image: busybox
        command: ["sh", "-c", "echo Hello Kubernetes! && sleep 240"]
      restartPolicy: OnFailure


